OPENAI_API_KEY=""
TOGETHER_API_KEY="b0f28c7123211058f7fbfab291c267502fb3f54c73a22792ddfcbcb6429a41d1"
TOGETHER_BASE_URL="https://api.together.xyz"
ANYSCALE_API_KEY=""
ANYSCALE_BASE_URL="https://api.endpoints.anyscale.com/v1"